import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'
export const fetchCache = 'force-no-store'

/**
 * GET /api/tags
 * 
 * Get all tags (public endpoint)
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createServerSupabaseClient()
    
    if (!supabase) {
      return NextResponse.json(
        { error: 'Service unavailable' },
        { status: 503 }
      )
    }

    const { searchParams } = new URL(request.url)
    const search = searchParams.get('search') || ''
    const limit = parseInt(searchParams.get('limit') || '50')

    let query = supabase
      .from('tags')
      .select('*')
      .order('name', { ascending: true })
      .limit(limit)

    // Add search filter if provided
    if (search) {
      query = query.ilike('name', `%${search}%`)
    }

    const { data: tags, error } = await query

    if (error) {
      console.error('Error fetching tags:', error)
      return NextResponse.json(
        { error: 'Failed to fetch tags', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({ tags: tags || [] })
  } catch (error: any) {
    console.error('Error in GET /api/tags:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    )
  }
}

/**
 * POST /api/tags
 * 
 * Create a new tag (admin only)
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createServerSupabaseClient()
    
    if (!supabase) {
      return NextResponse.json(
        { error: 'Service unavailable' },
        { status: 503 }
      )
    }

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    // Check if user is admin
    const { data: adminRole } = await supabase
      .from('admin_roles')
      .select('role')
      .eq('user_id', user.id)
      .eq('role', 'admin')
      .single()

    if (!adminRole) {
      return NextResponse.json(
        { error: 'Forbidden - Admin access required' },
        { status: 403 }
      )
    }

    // Parse request body
    const body = await request.json()
    const { name, description, color } = body as {
      name: string
      description?: string
      color?: string
    }

    if (!name || name.trim().length === 0) {
      return NextResponse.json(
        { error: 'Tag name is required' },
        { status: 400 }
      )
    }

    // Create tag (slug will be auto-generated by trigger)
    const { data: tag, error: tagError } = await supabase
      .from('tags')
      .insert({
        name: name.trim(),
        description: description?.trim() || null,
        color: color || null,
      })
      .select()
      .single()

    if (tagError) {
      console.error('Error creating tag:', tagError)
      
      // Handle duplicate tag name
      if (tagError.code === '23505') {
        return NextResponse.json(
          { error: 'Tag with this name already exists' },
          { status: 409 }
        )
      }

      return NextResponse.json(
        { error: 'Failed to create tag', details: tagError.message },
        { status: 500 }
      )
    }

    return NextResponse.json({ tag }, { status: 201 })
  } catch (error: any) {
    console.error('Error in POST /api/tags:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    )
  }
}

